import { ReportData } from './types';

export const reportData: ReportData = {
  currentPeriodId: 'q1-jun-2026',
  periods: [
    {
      id: 'q1-jun-2026',
      title: '21/07',
      overview: {
        consolidated: {
          engajamento: '2,70%',
          alcance: '1.613.197',
          interacoes: '52.503',
          impressoes: '2.414.395',
        },
        facebook: {
          engajamento: '1,24%',
          alcance: '90.475',
          alcanceMedia: '10.510',
          interacoes: '1.420',
          interacoesMedia: '114',
          impressoes: '110.482',
          impressoesMedia: '12.348',
        },
        instagram: {
          engajamento: '2,51%',
          alcance: '1.512.043',
          alcanceMedia: '60.481',
          interacoes: '50.399',
          interacoesMedia: '2.015',
          impressoes: '2.103.552',
          impressoesMedia: '84.142',
        },
        tiktok: {
          engajamento: '4,07%',
          alcance: '10.679',
          alcanceMedia: '711',
          interacoes: '684',
          interacoesMedia: '45',
          impressoes: '-',
          impressoesMedia: '-',
        },
        topPost: {
          id: 'igs-new-8',
          network: 'Instagram Stories',
          formato: 'Stories',
          imageUrl: 'https://i.imgur.com/cp7SsSL.png',
          title: '',
          date: '10/07/2026',
          alcance: '84.357',
          interacoes: '4.265',
          impressoes: '101.913',
          engajamento: '5,06%',
        },
      },
      networks: {
        facebook: {
          name: 'Facebook',
          analysis: 'Apresentou a menor taxa de engajamento médio entre as redes (0,61%).\n\nO post com sazonalidade tem alcance maior.\n\nTodas as publicações listadas foram realizadas exclusivamente de forma orgânica.',
          topPost: {
            id: 'fb-1',
            imageUrl: 'https://i.imgur.com/V65pSmb.png',
            title: '',
            date: '02 Jun 2026',
            alcance: '7.487',
            interacoes: '46',
            impressoes: '11.137',
            engajamento: '0,61%',
            formato: 'Carrossel',
          },
          posts: [
            {
              id: 'fb-new-1',
              date: '20/03/2026',
              grupo: 'Ifood',
              subgrupo: 'Economizasso',
              alcance: '8.016',
              interacoes: '110',
              curtidas: '89',
              comentarios: '7',
              impressoes: '10.227',
              link: 'link',
              engajamento: '1,37%',
              status: 'Orgânico',
            },
            {
              id: 'fb-new-2',
              date: '21/03/2026',
              grupo: 'Faro | Ifood',
              subgrupo: 'Economizasso',
              alcance: '5.427',
              interacoes: '67',
              curtidas: '89',
              comentarios: '3',
              impressoes: '6.166',
              link: 'link',
              engajamento: '1,23%',
              status: 'Orgânico',
            },
            {
              id: 'fb-new-3',
              date: '28/03/2026',
              grupo: 'Ifood',
              subgrupo: 'Acelera com Preço Baixo',
              alcance: '7.390',
              interacoes: '75',
              curtidas: '62',
              comentarios: '8',
              impressoes: '9.871',
              link: 'link',
              engajamento: '1,03%',
              status: 'Orgânico',
            },
            {
              id: 'fb-new-4',
              date: '02/05/2026',
              grupo: 'Páscoa Ifood',
              subgrupo: 'Ifood',
              alcance: '10.370',
              interacoes: '113',
              curtidas: '92',
              comentarios: '7',
              impressoes: '13.897',
              link: 'link',
              engajamento: '1,09%',
              status: 'Orgânico',
            },
            {
              id: 'fb-new-5',
              date: '29/05/2026',
              grupo: 'Começou | Ifood',
              subgrupo: 'Acelera com Preço Baixo',
              alcance: '7.487',
              interacoes: '46',
              curtidas: '45',
              comentarios: '1',
              impressoes: '11.137',
              link: 'link',
              engajamento: '0,61%',
              status: 'Orgânico',
            }
          ],
        },
        instagramFeed: {
          name: 'Instagram Feed',
          analysis: 'O Feed gerou mais de 1,35 milhão de alcance, principal canal de visibilidade.\n\nConteúdos com funcionários (Humanização e Reels) alcançam mais pessoas.\n\nO posts de sazonais como no Facebook, no feed alcançou pessoas, e mostra consistência.',
          topPost: {
            id: 'igf-1',
            imageUrl: 'https://i.imgur.com/V65pSmb.png',
            title: '',
            date: '29 May 2026',
            alcance: '26.554',
            interacoes: '150',
            impressoes: '55.979',
            engajamento: '0,56%',
            formato: 'Carrossel',
          },
          posts: [
            {
              id: 'igf-new-1',
              date: '21/03/2026',
              grupo: 'Rodrigo Faro | Ifood',
              subgrupo: 'Economizasso',
              alcance: '26.902',
              interacoes: '132',
              curtidas: '116',
              comentarios: '2',
              envios: '11',
              salvos: '3',
              impressoes: '31.172',
              link: 'link',
              engajamento: '0,49%',
              status: '-',
              formato: 'Reels',
            },
            {
              id: 'igf-new-2',
              date: '24/03/2026',
              grupo: 'Ifood',
              subgrupo: 'Sacolas',
              alcance: '47.561',
              interacoes: '439',
              curtidas: '271',
              comentarios: '142',
              envios: '26',
              salvos: '0',
              impressoes: '104.177',
              link: 'link',
              engajamento: '0,92%',
              status: '-',
              formato: 'Carrossel',
            },
            {
              id: 'igf-new-3',
              date: '28/03/2026',
              grupo: 'Ifood',
              subgrupo: 'Acelera com Preço Baixo',
              alcance: '37.330',
              interacoes: '196',
              curtidas: '173',
              comentarios: '7',
              envios: '12',
              salvos: '4',
              impressoes: '77.498',
              link: 'link',
              engajamento: '0,53%',
              status: '-',
              formato: 'Carrossel',
            },
            {
              id: 'igf-new-4',
              date: '06/05/2026',
              grupo: 'Páscoa Ifood',
              subgrupo: 'Ifood',
              alcance: '46.541',
              interacoes: '213',
              curtidas: '169',
              comentarios: '23',
              envios: '9',
              salvos: '12',
              impressoes: '68.517',
              link: 'link',
              engajamento: '0,46%',
              status: '-',
              formato: 'Estático',
            },
            {
              id: 'igf-new-5',
              date: '29/05/2026',
              grupo: 'Começou | Ifood',
              subgrupo: 'Acelera com Preço Baixo',
              alcance: '26.554',
              interacoes: '150',
              curtidas: '129',
              comentarios: '12',
              envios: '4',
              salvos: '5',
              impressoes: '55.979',
              link: 'link',
              engajamento: '0,56%',
              status: '-',
              formato: 'Carrossel',
            }
          ],
        },
        instagramStories: {
          name: 'Instagram Stories',
          analysis: 'Conciliar com campanhas ativas ou data sazonal, performa bem, exemplo o top post da semana que atinge 3,51% de engajamento médio.\n\nTema de bebida se mostra em alta no período atual, a presença em peças potencializa a performance.\n\nConteúdos com funcionários (Humanização e Reels) obtêm o maior alcance.',
          topPost: {
            id: 'igs-new-8',
            imageUrl: 'https://i.imgur.com/cp7SsSL.png',
            title: '',
            date: '10/07/2026',
            alcance: '84.357',
            interacoes: '4.265',
            impressoes: '101.913',
            engajamento: '5,06%',
            formato: 'Stories',
          },
          posts: [
            {
              id: 'igs-new-1',
              date: '21/03/2026',
              grupo: 'Faro | Ifood',
              subgrupo: 'Economizasso',
              alcance: '58.764',
              interacoes: '2.451',
              respostas: '11',
              envios: '8',
              cliquesLink: '1.515',
              impressoes: '67.859',
              engajamento: '4,17%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-2',
              date: '27/03/2026',
              grupo: 'Ifood | Sacolas',
              subgrupo: 'Acelera com Preço Baixo',
              alcance: '109.255',
              interacoes: '5.094',
              respostas: '11',
              envios: '12',
              cliquesLink: '3.122',
              impressoes: '133.251',
              engajamento: '4,66%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-3',
              date: '06/05/2026',
              grupo: 'Ifood',
              subgrupo: 'Ifood',
              alcance: '138.625',
              interacoes: '8.942',
              respostas: '46',
              envios: '16',
              cliquesLink: '4.633',
              impressoes: '169.984',
              engajamento: '6,45%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-4',
              date: '29/05/2026',
              grupo: 'Ifood',
              subgrupo: 'São João',
              alcance: '69.870',
              interacoes: '1.673',
              respostas: '11',
              envios: '04',
              cliquesLink: '926',
              impressoes: '74.063',
              engajamento: '2,39%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-5',
              date: '05/06/2026',
              grupo: 'Ifood',
              subgrupo: 'Ifood',
              alcance: '76.191',
              interacoes: '3.731',
              respostas: '8',
              envios: '2',
              cliquesLink: '2.451',
              impressoes: '89.104',
              engajamento: '4,90%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-6',
              date: '19/06/2026',
              grupo: 'Ifood',
              subgrupo: 'Copa Junina',
              alcance: '63.766',
              interacoes: '672',
              respostas: '4',
              envios: '1',
              cliquesLink: '571',
              impressoes: '76.695',
              engajamento: '1,05%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-7',
              date: '26/06/2026',
              grupo: 'Ifood',
              subgrupo: 'Acelera com Preço Baixo',
              alcance: '57.305',
              interacoes: '2.011',
              respostas: '7',
              envios: '1',
              cliquesLink: '1.927',
              impressoes: '66.102',
              engajamento: '3,51%',
              status: '-',
              formato: 'Stories',
            },
            {
              id: 'igs-new-8',
              date: '10/07/2026',
              grupo: 'IFOOD',
              subgrupo: 'Leva que vale',
              alcance: '84.357',
              interacoes: '4.265',
              respostas: '7',
              envios: '5',
              cliquesLink: '3.285',
              impressoes: '101.913',
              engajamento: '5,06%',
              status: '-',
              formato: 'Stories',
            }
          ],
        },
        tiktok: {
          name: 'TikTok',
          analysis: 'O post teve performance abaixo da media dos anteriores, a estética ficou muito artificial e a presença humana que é uma característica forte não apareceu muito.\n\nO post de alguma forma deve ser desenvolvido para trazer a interação, focar na interação é a chave para uma maior distribuição do conteúdo.\n\nA performance por campanha valida a estratégia de humanização do conteúdo, apontando-a como o principal motor para atrair mais interações.',
          topPost: {
            id: 'tk-new-8',
            imageUrl: 'https://i.imgur.com/cp7SsSL.png',
            title: '',
            date: '10/07/2026',
            visualizacoes: '361',
            interacoes: '23',
            engajamento: '6,37%',
            formato: 'Video',
          },
          posts: [
            {
              id: 'tk-new-1',
              date: '13/03/2026',
              grupo: 'Ifood',
              subgrupo: 'Ifood',
              visualizacoes: '892',
              interacoes: '28',
              curtidas: '22',
              comentarios: '3',
              compartilhamentos: '3',
              link: 'Link',
              engajamento: '4,05%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-2',
              date: '20/03/2026',
              grupo: 'Ifood | Funcionário',
              subgrupo: 'Economizasso',
              visualizacoes: '1.188',
              interacoes: '45',
              curtidas: '41',
              comentarios: '2',
              compartilhamentos: '2',
              link: 'Link',
              engajamento: '3,79%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-3',
              date: '21/03/2026',
              grupo: 'Rodrigo Faro | Ifood',
              subgrupo: 'Economizasso',
              visualizacoes: '787',
              interacoes: '35',
              curtidas: '33',
              comentarios: '1',
              compartilhamentos: '1',
              link: 'Link',
              engajamento: '4,45%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-4',
              date: '02/05/2026',
              grupo: 'Páscoa Ifood',
              subgrupo: 'Ifood',
              visualizacoes: '835',
              interacoes: '27',
              curtidas: '25',
              comentarios: '1',
              compartilhamentos: '1',
              link: 'Link',
              engajamento: '3,23%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-5',
              date: '05/05/2026',
              grupo: 'Ifood | Funcionário',
              subgrupo: 'Copa da Torcida',
              visualizacoes: '2.693',
              interacoes: '116',
              curtidas: '111',
              comentarios: '4',
              compartilhamentos: '1',
              link: 'Link',
              engajamento: '4,31%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-6',
              date: '19/06/2026',
              grupo: 'Rodrigo Faro | Ifood',
              subgrupo: 'Ifood',
              visualizacoes: '1.078',
              interacoes: '50',
              curtidas: '44',
              comentarios: '4',
              compartilhamentos: '2',
              link: 'Link',
              engajamento: '4,64%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-7',
              date: '21/06/2026',
              grupo: 'Fun',
              subgrupo: 'Ifood',
              visualizacoes: '660',
              interacoes: '19',
              curtidas: '19',
              comentarios: '0',
              compartilhamentos: '0',
              link: 'Link',
              engajamento: '2,88%',
              status: 'Orgânico',
            },
            {
              id: 'tk-new-8',
              date: '10/07/2026',
              grupo: 'IFOOD',
              subgrupo: 'Leva que vale',
              visualizacoes: '361',
              interacoes: '23',
              curtidas: '21',
              comentarios: '1',
              compartilhamentos: '1',
              link: 'Link',
              status: 'Link',
              engajamento: '6,37%',
            }
          ],
        },
      },
    },
  ],
};
